
Content-Type: text/html

<body bgcolor="#f0f0f8"><font color="#f0f0f8" size="-5"> -->
<body bgcolor="#f0f0f8"><font color="#f0f0f8" size="-5"> --> -->
</font> </font> </font> </script> </object> </blockquote> </pre>
</table> </table> </table> </table> </table> </font> </font> </font><body bgcolor="#f0f0f8">
<table width="100%" cellspacing=0 cellpadding=2 border=0 summary="heading">
<tr bgcolor="#6622aa">
<td valign=bottom>&nbsp;<br>
<font color="#ffffff" face="helvetica, arial">&nbsp;<br><big><big><strong>KeyError</strong></big></big></font></td
><td align=right valign=bottom
><font color="#ffffff" face="helvetica, arial">Python 2.4.4: /usr/bin/python<br>Wed Mar 24 22:02:49 2010</font></td></tr></table>
    
<p>A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.</p>
<table width="100%" cellspacing=0 cellpadding=0 border=0>
<tr><td bgcolor="#d8bbff"><big>&nbsp;</big><a href="file:///home/shanxi/cameronboehmer.com/twitter/proxy.py">/home/shanxi/cameronboehmer.com/twitter/proxy.py</a> </td></tr>
<tr><td><font color="#909090"><tt><small>&nbsp;&nbsp;&nbsp;&nbsp;5</small>&nbsp;import&nbsp;cgi,&nbsp;cgitb;&nbsp;cgitb.enable()<br>
</tt></font></td></tr>
<tr><td><font color="#909090"><tt><small>&nbsp;&nbsp;&nbsp;&nbsp;6</small>&nbsp;<br>
</tt></font></td></tr>
<tr><td><font color="#909090"><tt><small>&nbsp;&nbsp;&nbsp;&nbsp;7</small>&nbsp;form&nbsp;=&nbsp;dict([(k,v.value)&nbsp;for&nbsp;k,v&nbsp;in&nbsp;dict(cgi.FieldStorage()).iteritems()])<br>
</tt></font></td></tr>
<tr><td bgcolor="#ffccee"><tt><small>&nbsp;&nbsp;&nbsp;&nbsp;8</small>&nbsp;phone&nbsp;=&nbsp;TweetPhone(form.pop('user'),&nbsp;form.pop('pass'))<br>
</tt></td></tr>
<tr><td><font color="#909090"><tt><small>&nbsp;&nbsp;&nbsp;&nbsp;9</small>&nbsp;print&nbsp;phone.call(form.pop('method'),&nbsp;form)<br>
</tt></font></td></tr>
<tr><td><small><font color="#909090">phone <em>undefined</em>, <strong>TweetPhone</strong>&nbsp;= &lt;class 'TweetPhone.TweetPhone'&gt;, <strong>form</strong>&nbsp;= {'method': 'statuses/update', 'status': 'hallo'}, form.<strong>pop</strong>&nbsp;= &lt;built-in method pop of dict object&gt;</font></small></td></tr></table><p><strong>KeyError</strong>: 'user'
<br><tt><small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</small>&nbsp;</tt>args&nbsp;=
('user',)


<!-- The above is a description of an error in a Python program, formatted
     for a Web browser because the 'cgitb' module was enabled.  In case you
     are not reading this in a Web browser, here is the original traceback:

Traceback (most recent call last):
  File "proxy.py", line 8, in ?
    phone = TweetPhone(form.pop('user'), form.pop('pass'))
KeyError: 'user'


